# Generated by Django 5.1.3 on 2024-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой')], default='small', max_length=6, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='size_limit',
            field=models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой')], default='small', max_length=6, verbose_name='Размер стеллажа'),
        ),
    ]
