# Generated by Django 5.1.3 on 2024-11-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shelf_max_capacity_alter_shelf_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shelf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shelf', verbose_name='Стеллаж'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='max_capacity',
            field=models.PositiveIntegerField(verbose_name='Максимальная вместимость'),
        ),
    ]
