# Generated by Django 5.1.3 on 2024-11-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_shelf_alter_shelf_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shelf', verbose_name='Стеллаж'),
        ),
    ]
