# Generated by Django 5.1.3 on 2024-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_shelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='action',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='data',
            field=models.TextField(default='', verbose_name='Данные'),
        ),
    ]
