# Generated by Django 5.1.3 on 2024-11-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_journalentry_action_remove_journalentry_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='operation_type',
            field=models.CharField(choices=[('приход', 'приход'), ('уход', 'уход')], default='приход', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
